version: "3.7"
services:
  react-dev:
    container_name: docker-react
    build:
      context: .
      # the dockerfile to be run
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development